pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: stage.etelaranta.net
    username: root
    port: 22
    secrets: [ssh_key]
    script:
      - ./deploy.sh
    when:
      branch: ["master", "dev"]
      event: [push]