FROM node:alpine as builder

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN yarn install
RUN yarn workspace @er/ui docs:build

FROM nginx

RUN rm -r /etc/nginx/conf.d

COPY packages/ui/config/nginx /etc/nginx/conf.d

COPY --from=builder /app/packages/ui/dist /app
